# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ish', '0003_auto_20170425_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_text',
        ),
    ]
