# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ish', '0004_remove_user_password_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_signup',
        ),
    ]
