# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ish', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
