# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ish', '0007_remove_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
